name: CI & Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# don't run two deploys at once for the same branch
concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run tests
        run: mvn -B -ntp test

  deploy:
    name: Deploy to Render (clean build via API)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    env:
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      # optional secret to toggle cache clearing; defaults to true
      CLEAR_CACHE: ${{ secrets.RENDER_CLEAR_CACHE || 'true' }}
      COMMIT_ID: ${{ github.sha }}

    steps:
      - name: Validate required secrets
        run: |
          set -euo pipefail
          [ -n "${RENDER_SERVICE_ID:-}" ] || { echo "Missing secret: RENDER_SERVICE_ID"; exit 1; }
          [ -n "${RENDER_API_KEY:-}" ]   || { echo "Missing secret: RENDER_API_KEY"; exit 1; }

      - name: Normalize CLEAR_CACHE to boolean
        id: norm
        run: |
          cc=false
          case "${CLEAR_CACHE,,}" in
            true|1|yes|y) cc=true ;;
          esac
          echo "cc=$cc" >> "$GITHUB_OUTPUT"

      - name: Trigger Render deploy (clean build)
        id: trigger
        run: |
          set -euo pipefail
          # Build JSON safely with jq
          payload=$(jq -n \
            --arg commitId "${COMMIT_ID}" \
            --argjson clearCache "${{ steps.norm.outputs.cc }}" \
            '{commitId: $commitId, clearCache: $clearCache}')
          echo "Payload: $payload"

          resp=$(curl -sS -X POST \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$payload")

          echo "API response: $resp"

          id=$(echo "$resp" | jq -r '.id // empty')
          [ -n "$id" ] || { echo "Failed to trigger deploy"; exit 1; }
          echo "deploy_id=$id" >> "$GITHUB_OUTPUT"

      - name: Wait until Live
        run: |
          set -euo pipefail
          id="${{ steps.trigger.outputs.deploy_id }}"
          echo "Waiting for deploy: $id"

          for i in $(seq 1 120); do
            resp=$(curl -sS -H "Authorization: Bearer ${RENDER_API_KEY}" \
              "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys/$id")
            status=$(echo "$resp" | jq -r '.status')
            echo "[$i] status=$status"

            case "$status" in
              live)     echo "Deploy is live ✅"; exit 0 ;;
              failed)   echo "Deploy failed ❌"; echo "$resp"; exit 1 ;;
              canceled) echo "Deploy canceled 🛑"; echo "$resp"; exit 1 ;;
            esac

            sleep 10
          done

          echo "Timeout waiting for deploy to go live"; exit 1
